git clone "nombre del repositorio"      (bajar datos del repositorio)
git add "nombre"                        (aderir archivos a proyecto)
git add .                               (aderir todo lo que este en la carpeta al proyecto)
git status                              (consultar cambios en proyecto ramaq)
git commit                              (guardar cambios en proyecto rama)
git pull                                (bajar cambios de rama)
git push                                (subir cambios a rama)
git branch                              (ver ramas)
git checkout "rama"                     (cambiar de rama)
git fetch                               (bajar ramas que estan arriba)
git branch -r                           (ver ramas que estan arriba)
git log                                 (ver los cambios en la ramma en el tiempo)
git log --oneline                       (ver los cambios en la ramma mas ordenado)
git log --oneline --graph               (ver los cambios en la ramma con grafico)
